name: Deploy to EC2
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Build and push Docker image
      run: |
        docker build -t suhasc/dummy-server .
        #docker tag dummy-server:latest suhasc/dummy-server:latest
        docker login -u suhasc -p ${{ secrets.DOCKER_PASSWORD }}
        docker push suhasc/dummy-server:latest
